# Generated by Django 5.1.2 on 2024-10-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('mens', "Men's Clothing"), ('womens', "Women's Clothing"), ('kids', "Kids' Clothing"), ('others', 'Others')], max_length=20, unique=True),
        ),
    ]
