# Generated by Django 5.1.2 on 2024-10-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_product_brand_delete_brand 2'),
        ('myapp', '0005_remove_product_brand_delete_brand'),
    ]

    operations = [
    ]
